name: "Pull Request or Push"

on:
  push:
    branches:
      - '*'
  pull_request:
      branches:
        - '*'

jobs:
  on-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: "Print New Commit comming"
        run: echo "New Commit comming, Workflow runs on any branch"


  on-pull_request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: "Print New Commit comming"
        run: echo "New Commit comming, Workflow runs on any branch"